spring.application.name=Farmer-ConnectSP

#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/Farmer-Connect
#spring.datasource.username=root
#spring.datasource.password=root

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/Farmer_connect
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=400MB
spring.servlet.multipart.resolve-lazily=true
#spring.servlet.multipart.max-file-count=20


#server.tomcat.max-http-form-post-size=1000MB

#server.tomcat.max-parameter-count=10000

#server.tomcat.max-swallow-size=20MB

#server.tomcat.max-parameters=20
#server.tomcat.max-http-form-post-size=30MB
#server.tomcat.max-swallow-size=-1

#project.image=/images/
#
#file.upload.profile=uploads/profiles

#email configuaration

#spring:mail:host:smtp.email.com
#sping :mail:port:587
#spring:mail:password:clan jiix obzr bxnx

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=loharprem471@gmail.com
spring.mail.password=clan jiix obzr bxnx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=${PORT:8080}